#!/usr/bin/env bash

if [ -z "${1}" ]; then
    echo Please specify outputfolder as positional argument.
    exit
fi

lumi=59.74
outputdir="${1}"


# Signal
./makeBinYields.py \
    --mca mca/2018/mca-Autumn18_Signal.txt \
    --signal \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/scan

# Background
./makeBinYields.py \
    --mca mca/2018/mca-Autumn18.txt \
    --grid \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/grid

# Background with dilepton nJet correction
./makeBinYields.py \
    --mca mca/2018/mca-Autumn18_dilep-corr.txt \
    --grid \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/grid-dilep

# Systematic: dilepton constant
./makeBinYields.py \
    --mca ../systs/2018/DLConst/mca-Autumn18.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_DLConst

# Systematic: dilepton slope
./makeBinYields.py \
    --mca ../systs/2018/DLSlope/mca-Autumn18.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_DLSlope

# Systematic: JEC
./makeBinYields.py \
    --mca ../systs/2018/JEC/mca-Autumn18.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_JEC

## Systematic: PDF
#./makeBinYields.py \
#    --mca ../systs/PDFUnc-RMS/mca-Autumn18_Moriond17.txt \
#    --grid \
#    --systs True \
#    -v 2 \
#    -l "${lumi}" \
#    -b \
#    --od "${outputdir}"/syst_PDFUnc-RMS

## Systematic: scale match
#./makeBinYields.py \
#    --mca ../systs/ScaleMatchVar/mca-Autumn18_Moriond17.txt \
#    --grid \
#    --systs True \
#    -v 2 \
#    -l "${lumi}" \
#    -b \
#    --od "${outputdir}"/syst_ScaleMatchVar


# Systematic: W polarization
./makeBinYields.py \
    --mca ../systs/2018/Wpol/mca-Autumn18.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_Wpol

# Systematic: W cross section
./makeBinYields.py \
    --mca ../systs/2018/Wxsec/mca-Autumn18.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_Wxsec

# Systematic: b-tagging heavy flavour
./makeBinYields.py \
    --mca ../systs/2018/btagHF/mca-Autumn18.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_btagHF

# Systematic: b-tagging
./makeBinYields.py \
    --mca ../systs/2018/btagLF/mca-Autumn18.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_btagLF

# Systematic: lepton SF
./makeBinYields.py \
    --mca ../systs/2018/lepSF/mca-Autumn18.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_lepSF

# Systematic: pileup
./makeBinYields.py \
    --mca ../systs/2018/PU/mca-Autumn18.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_PU

# Systematic: TTV cross section
./makeBinYields.py \
    --mca ../systs/2018/TTVxsec/mca-Autumn18.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_TTVxsec

# Systematic: TT cross section
./makeBinYields.py \
    --mca ../systs/2018/TTxsec/mca-Autumn18.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_TTxsec

## Systematic: nISR reweighting
#./makeBinYields.py \
#    --mca ../systs/2018/nISR/mca-Autumn18.txt \
#    --grid \
#    --systs True \
#    -v 2 \
#    -l "${lumi}" \
#    -b \
#    --od "${outputdir}"/syst_nISR


# Signal systematic: Gluino ISR
./makeBinYields.py \
    --mca ../systs/2018/signal/ISR/mca-Autumn18_Signal.txt \
    --signal \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/signal_ISR

# Signal systematic: JEC
./makeBinYields.py \
    --mca ../systs/2018/signal/JEC/mca-Autumn18_Signal.txt  \
    --signal \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/signal_JEC

# Signal systematic: btag heavy flavour
./makeBinYields.py \
    --mca ../systs/2018/signal/btagHF/mca-Autumn18_Signal.txt  \
    --signal \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/signal_btagHF
 
# Signal systematic: btag light flavour
./makeBinYields.py \
    --mca ../systs/2018/signal/btagLF/mca-Autumn18_Signal.txt  \
    --signal \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/signal_btagLF
 





# does not work out of the box, because the new signal samples are not in 
# the same place as the old ones (yet) and the paths are hardcoded in 
# makeBinYields
## Signal systematic: scale variation
#./makeBinYields.py \
#    --mca ../systs/signal/scale/mca-Autumn18_Signal_forMoriond17.txt  \
#    --signal \
#    --systs True \
#    -v 2 \
#    -l "${lumi}" \
#    -b \
#    --od "${outputdir}"/signal_scale

## Signal systematic: pileup
#./makeBinYields.py \
#    --mca ../systs/signal/PU/mca-Autumn18_Signal_forMoriond17.txt  \
#    --signal \
#    --systs True \
#    -v 2 \
#    -l "${lumi}" \
#    -b \
#    --od "${outputdir}"/signal_PU

