#!/usr/bin/env bash

# Stop when an error occurs
set -e -o pipefail

# User needs to specify input folder
if [ -z "${1}" ]; then
    echo Please specify input folder as positional argument.
    exit
fi

# Pipe all output also to logfile
exec > >(tee -i log.out)
exec 2>&1

# Input folder is first positional argument, need to strip possible trailing "/"
# to prevent problems later
inputfolder="${1%/}"

# Merge bins
echo Run mergeBins_0b.py
for folder in "${inputfolder}"/*; do
    # If merged folder already exists, skip
    if [[ -d "${folder}"/merged/ ]]; then
        continue
    fi
    ./mergeBins_0b.py "${folder}/LT"
done

## Append Rcs kappa
echo Run appendRcsKappa_0b.py
for folder in "${inputfolder}"/*/merged*; do
    echo $folder
    #Skip signal folder
    if [[ "${folder}" == */scan/* ]]; then
        echo "scan"
        continue
    fi
    if [[ "${folder}" == */grid/* ]]; then
        echo "scan"
        continue
    fi
    #Predict backgrounds
    if [[ "${folder}" == */*/merged ]]; then
        echo ./appendRcsKappa_0b.py "${folder}/LT"
        ./appendRcsKappa_0b.py "${folder}"
    fi
    #Only do qcd estimate for SB, this is only needed for plotting and calculating Rcs here does not make sense
    if [[ "${folder}" == */*/mergedNJ* ]]; then
        echo ./appendRcsKappa_0b.py "${folder}/LT" --do-qcd
        ./appendRcsKappa_0b.py "${folder}" --do-qcd
    fi
done

# Calculate the systematic variations
# Takes up and down histograms and creates syst histograms
echo Run calcSyst.py
./calcSyst_0b.py "${inputfolder}"

# Write table with systematic variations that is used by makeYieldTables.py
echo Run tableSyst.py
./tableSyst_0b.py "${inputfolder}"

echo Run plotSysts
./plotSyst_0b.py "${inputfolder}"

## Write tables
#echo Run makeYieldTables.py
#./makeYieldTables.py "${inputfolder}"
#
## Plot data with prediction, but no systematics
#echo Run plotDataPredict.py
#for folder in "${inputfolder}"/grid-dilep/merged*; do
#    ./plotDataPredict.py -b "${folder}"/LT
#done
#
## Plot data with prediction, with systematics
#echo Run plotDataPredictWithSyst.py
##Pantelis for folder in merged merged4f5 mergedFew; do
#for folder in merged; do
#    ./plotDataPredictWithSyst.py -b "${inputfolder}" "${folder}"
#done
#
## Plot Rcs and kappa without systematics
#echo Run plotRcsKappa.py
#for folder in "${inputfolder}"/grid-dilep/merged*; do
#    ./plotRcsKappa.py -b "${folder}"/LT
#done
#
## Plot with uncertainties with kappa in the bottom panel
#echo Run plotSyst.py
#./plotSyst.py -b "${inputfolder}"

## Plot signal uncertainties with yields in bottom panel
#echo Run plotSigSyst.py
#./plotSigSyst.py -b "${inputfolder}"
#
## Compare something
##python plotCompare.py LT
#
##python makeRCSplots.py indir/grid
##python averageSig.py LT
