#!/usr/bin/env bash

if [ -z "${1}" ]; then
    echo Please specify outputfolder as positional argument.
    exit
fi

lumi=35.9
outputdir="${1}"

### Signal
./makeBinYields_0b.py \
    --mca mca/2016_EXT/mca-Spring16_Signal_0b.txt \
    --signal \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/scan

### Background
./makeBinYields_0b.py \
    --mca mca/2016_EXT/mca-Summer16_0b.txt \
    --grid \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/grid

#### Background with dilepton nJet correction
./makeBinYields_0b.py \
    --mca mca/2016_EXT/mca-Summer16_0b_dilep-corr.txt \
    --grid \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/grid-dilep

# Systematic: dilepton constant
./makeBinYields_0b.py \
    --mca ../systs/2016_EXT/DLConst/mca-Summer16.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_DLConst

# Systematic: dilepton slope
./makeBinYields_0b.py \
    --mca ../systs/2016_EXT/DLSlope/mca-Summer16.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_DLSlope

# Systematic: JEC
./makeBinYields_0b.py \
    --mca ../systs/2016_EXT/JEC/mca-Summer16.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_JEC

# Systematic: PDF
./makeBinYields_0b.py \
    --mca ../systs/PDFUnc-RMS/mca-Summer16_Moriond17.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_PDFUnc-RMS

# Systematic: scale match
./makeBinYields_0b.py \
    --mca ../systs/ScaleMatchVar/mca-Summer16_Moriond17.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_ScaleMatchVar


# Systematic: W polarization
./makeBinYields_0b.py \
    --mca ../systs/2016_EXT/Wpol/mca-Summer16.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_Wpol

# Systematic: W cross section
./makeBinYields_0b.py \
    --mca ../systs/2016_EXT/Wxsec/mca-Summer16.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_Wxsec

# Systematic: b-tagging heavy flavour
./makeBinYields_0b.py \
    --mca ../systs/2016_EXT/btagHF/mca-Summer16.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_btagHF

# Systematic: b-tagging
./makeBinYields_0b.py \
    --mca ../systs/2016_EXT/btagLF/mca-Summer16.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_btagLF

# Systematic: lepton SF
./makeBinYields_0b.py \
    --mca ../systs/2016_EXT/lepSF/mca-Summer16.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_lepSF

# Systematic: pileup
./makeBinYields_0b.py \
    --mca ../systs/2016_EXT/PU/mca-Summer16.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_PU

# Systematic: TTV cross section
./makeBinYields_0b.py \
    --mca ../systs/2016_EXT/TTVxsec/mca-Summer16.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_TTVxsec

# Systematic: TT cross section
./makeBinYields_0b.py \
    --mca ../systs/2016_EXT/TTxsec/mca-Summer16.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_TTxsec

# Systematic: nISR reweighting
./makeBinYields_0b.py \
    --mca ../systs/2016_EXT/nISR/mca-Summer16.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_nISR

# Signal systematic: Gluino ISR
./makeBinYields_0b.py \
    --mca ../systs/2016_EXT/signal/ISR/mca-Spring16_Signal.txt \
    --signal \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/signal_ISR

# Signal systematic: JEC
./makeBinYields_0b.py \
    --mca ../systs/2016_EXT/signal/JEC/mca-Spring16_Signal.txt  \
    --signal \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/signal_JEC

# Signal systematic: btag heavy flavour
./makeBinYields_0b.py \
    --mca ../systs/2016_EXT/signal/btagHF/mca-Spring16_Signal.txt  \
    --signal \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/signal_btagHF

# Signal systematic: btag light flavour
./makeBinYields_0b.py \
    --mca ../systs/2016_EXT/signal/btagLF/mca-Spring16_Signal.txt  \
    --signal \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/signal_btagLF






## does not work out of the box, because the new signal samples are not in
## the same place as the old ones (yet) and the paths are hardcoded in
## makeBinYields_0b
### Signal systematic: scale variation
##./makeBinYields_0b.py \
##    --mca ../systs/signal/scale/mca-Spring16_Signal_forMoriond17.txt  \
##    --signal \
##    --systs True \
##    -v 2 \
##    -l "${lumi}" \
##    -b \
##    --od "${outputdir}"/signal_scale
##
### Signal systematic: pileup
##./makeBinYields_0b.py \
##    --mca ../systs/signal/PU/mca-Spring16_Signal_forMoriond17.txt  \
##    --signal \
##    --systs True \
##    -v 2 \
##    -l "${lumi}" \
##    -b \
##    --od "${outputdir}"/signal_PU
