#!/usr/bin/env bash

# Script to make plots
# This needs to be called from $CMSSW_BASE/src/CMGTools/TTHAnalysis/python/plotter
# You need to have symbolic links called "trees" and "friends", pointing to your
# trees and friend trees, resp.

lumi=59.74

mca=susy-1lep/mca/2018_QCD/mca-Autumn18_forQCD_w_HEM_MC_SF_with_Ext.txt
cuts=susy-1lep/1l_basicCutsFullCutFlow_qcd-est_2018.txt

trees=/nfs/dust/cms/user/pakontax/CMSSW/Full_Run_II_Analysis_FINAL_FINAL_FINAL_17July2020/CMSSW_10_4_0/src/CMGTools/TTHAnalysis/python/plotter/susy-1lep/Softlinks/trees_2018_from_dCache_FINAL/

friends=/nfs/dust/cms/user/pakontax/CMSSW/Full_Run_II_Analysis_FINAL_FINAL_FINAL_17July2020/CMSSW_10_4_0/src/CMGTools/TTHAnalysis/python/plotter/susy-1lep/Softlinks/FRIENDS_2018_FINAL/evVarFriend_{cname}.root

# QCD estimation, define QCD as signal
python mcPlots.py \
    "${mca}" \
    "${cuts}" \
    susy-1lep/qcd-est/txtconfigs/Lp_LTbins_forFit_0b.txt \
    -P "${trees}" \
    -F sf/t "${friends}" \
    -l "${lumi}" \
    -j $(nproc) \
    --tree treeProducerSusySingleLepton \
    -G \
    -f \
    --showRatio \
    --maxRatioRange 0.05 1.95 \
    --fixRatioRange \
    --noErrorBandOnRatio \
    --noStackSig \
    --showIndivSigs \
